### ISSUE TITLE
conflict with pane management plugins

### ISSUE THREAD

**Issue by valkalon** [Kesin11/atom-vim-like-tab#15]
Hi !
first of all thanks a lot for your plugin, I was really looking forward to having the tab feature on atom.

I would like to use atom-vim-like-tab with pane management plugins such as pane-layout-plus or layout-control, but both of them conflict with atom-vim-like-tab.

https://atom.io/packages/pane-layout-plus
https://atom.io/packages/layout-control

# Steps to reproduce (using pane-layout-plus)
- open a second tab with atom-vim-like-tab 
- open a file in this tab
- use pane-layout-plus to change the pane layout to 2 panes

result : nothing happens
![peek_pane_layout_issue](https://user-images.githubusercontent.com/7339264/43039649-25a9dce6-8d32-11e8-908f-cc168dddee71.gif)

Similar issues happen with other pane layouts (3 panes, 4 panes...) and extra tabs.

- plugins:
├── atom-alignment@0.13.0
├── atom-language-rust@0.13.0
├── atom-vim-like-tab@1.5.2
├── autoclose-html@0.23.0
├── busy-signal@1.4.3
├── document-outline@2.1.2
├── emmet@2.4.3
├── expand-selection-to-quotes@0.11.0
├── intentions@1.1.5
├── jumpy@4.2.0
├── language-markdown@0.26.0
├── language-nginx@0.8.0
├── linter@2.2.0
├── linter-shellcheck@1.4.7
├── linter-ui-default@1.7.1
├── markdown-image-assistant@0.2.1
├── markdown-scroll-sync@2.1.2
├── monokai@0.24.0
├── open-recent@5.0.0
├── pane-layout-plus@0.7.4
├── php-twig@4.0.0
├── preview-inline@1.5.1
├── project-manager@3.3.6
├── recent-files-fuzzy-finder@0.6.1
├── symbols-navigator@1.4.0
├── tomorrow@1.0.0
└── tomorrow-night-eighties-syntax@1.1.0

- environment:
Ubuntu 16.04
Atom    : 1.28.1
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3

Do you think this issue can be solved ?

**Comment by Kesin11** [comment]
Thank you for your report. But I'm sorry I have no idea.
atom-vim-like-tab will change atom view HTML directly for emulate original vim tab when you create new tab (`atom-vim-like-tab:new`).

Therefore, it is prone to conflict with other pane management packages 😢

**Comment by valkalon** [comment]
I understand, no problem, Thank you for investigating it, very kind of you!
