### ISSUE TITLE
[BUG] Tabs don't persist across Atom restarts

### ISSUE THREAD

**Issue by nwaywood** [Kesin11/atom-vim-like-tab#6]
Steps to reproduce:

1. Create a second tab with `atom-vim-like-tab:new`
2. Open a file (any file) in the new tab
3. Quit Atom
4. Reopen Atom

On Atom restart the tabs are gone and all the files that were open across all tabs are in the one tab

**Comment by Kesin11** [comment]
Sorry, this plugin doesn't provide to restore tabs.
I tried to make this feature and gave up because it very difficult.
If someone implements this feature, I'll merge it 😄

**Comment by trusktr** [comment]
This would be cool! The next time we start Atom everything is in panes. It is awkward:

![screen shot 2018-05-28 at 11 02 25 pm](https://user-images.githubusercontent.com/297678/40640514-34ba42ac-62cb-11e8-9929-2c54213fe713.png)

Maybe for now, as a temporary solution, you can destroy all the tabs and close all the files? That way, at least we don't start with many panes all in one view.
